---

- name: Create redirectionio-agent configuration file
  template:
    src: agent.yml.j2
    dest: /etc/redirectionio/agent.yml
    owner: '{{ redirectionio_user }}'
    group: '{{ redirectionio_group }}'
    mode: 0644
  notify: restart redirectionio-agent
