---

- name: "Ensure {{ redirectionio_agent_log.file.path | dirname }} exists and is writable"
  file:
    path: '{{ redirectionio_agent_log.file.path | dirname }}'
    owner: '{{ redirectionio_user }}'
    group: '{{ redirectionio_group }}'
    mode: 0755
    state: directory
  changed_when: false
  when: redirectionio_agent_log.file is defined and redirectionio_agent_log.file.path is defined

- name: "Ensure {{ redirectionio_agent_log.file.path }} exists and is writable"
  ansible.builtin.file:
    path: '{{ redirectionio_agent_log.file.path }}'
    owner: '{{ redirectionio_user }}'
    group: '{{ redirectionio_group }}'
    mode: 0644
    state: touch
  changed_when: false
  when: redirectionio_agent_log.file is defined and redirectionio_agent_log.file.path is defined

- name: Set logrotate
  ansible.builtin.template:
    src: 'logrotate.j2'
    dest: /etc/logrotate.d/redirectionio-agent
    owner: root
    group: root
    mode: 0644
  when: redirectionio_agent_log.file is defined and redirectionio_agent_log.file.path is defined
