---

- name: Checking for configuration vars
  fail:
    msg: "{{ item }} has not been defined"
  when: "item is undefined"
  with_items:
    - redirectionio_agent_instance_name

- import_tasks: pkg-debian.yml
  when: ansible_os_family == "Debian"

- import_tasks: pkg-redhat.yml
  when: ansible_os_family == "RedHat"

- import_tasks: log.yml

- import_tasks: configure.yml
