---

- name: Checking for configuration vars
  fail:
    msg: "{{ item }} has not been defined"
  when: "item is undefined"
  with_items:
    - redirectionio_agent_instance_name

- name: Install for Debian
  ansible.builtin.import_tasks: pkg-debian.yml
  when: ansible_os_family == "Debian"

- name: Install for RedHat
  ansible.builtin.import_tasks: pkg-redhat.yml
  when: ansible_os_family == "RedHat"

- name: Configure logs
  ansible.builtin.import_tasks: log.yml

- name: Configure agent
  ansible.builtin.import_tasks: configure.yml
