---

- name: Install the apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: import redirection.io apt key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 24765BBD8E16EB44
    state: present

- name: Install redirection.io repository
  apt_repository:
    repo: "deb https://packages.redirection.io/deb any main"
    state: present
  when: redirectionio_agent_channel == ""

- name: Install redirection.io repository
  apt_repository:
    repo: "deb https://packages.redirection.io/deb/{{ redirectionio_agent_channel }}/{{ redirectionio_agent_main_version }} any main"
    state: present
  when: redirectionio_agent_channel != ""

- name: Update apt cache
  apt:
    update_cache: true

- name: Install redirectionio-agent
  apt:
    name: "redirectionio-agent={{ redirectionio_agent_version }}"
    state: present
  notify: restart redirectionio-agent
