---

- name: Add rpm repository key
  ansible.builtin.rpm_key:
    state: present
    key: http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x24765BBD8E16EB44

- name: Install redirection.io repository
  ansible.builtin.yum_repository:
    name: redirectionio
    description: redirection.io
    baseurl: "https://packages.redirection.io/rpm/any"
    enabled: true
    gpgcheck: true
    state: present
  when: redirectionio_agent_main_version == 1

- name: Install redirection.io repository
  ansible.builtin.yum_repository:
    name: redirectionio
    description: redirection.io
    baseurl: "https://packages.redirection.io/rpm/{{ redirectionio_agent_channel }}/{{ redirectionio_agent_main_version }}/any"
    enabled: true
    gpgcheck: true
    state: present
  when: redirectionio_agent_main_version > 1

- name: Update yum cache
  ansible.builtin.yum:
    update_cache: true

- name: Install redirectionio-agent
  ansible.builtin.yum:
    name: "redirectionio-agent-{{ redirectionio_agent_version }}"
    state: present
