---

- name: Install the apt-transport-https
  ansible.builtin.apt:
    name: apt-transport-https
    state: present

- name: Import redirection.io apt key
  ansible.builtin.get_url:
    url: "https://packages.redirection.io/gpg.key"
    dest: /etc/apt/keyrings/redirectionio-archive-keyring.asc
    mode: '0644'

- name: Get dpkg architecture
  ansible.builtin.command: dpkg --print-architecture
  register: dpkg_architecture
  changed_when: false

- name: Install redirection.io repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ dpkg_architecture.stdout }} signed-by=/etc/apt/keyrings/redirectionio-archive-keyring.asc]
      https://packages.redirection.io/deb
      any
      main
    state: present
  when: redirectionio_agent_main_version == 1

- name: Install redirection.io repository
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch={{ dpkg_architecture.stdout }} signed-by=/etc/apt/keyrings/redirectionio-archive-keyring.asc]
      https://packages.redirection.io/deb/{{ redirectionio_agent_channel }}/{{ redirectionio_agent_main_version }}
      any
      main
    state: present
  when: redirectionio_agent_main_version > 1

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install redirectionio-agent
  ansible.builtin.apt:
    name: "redirectionio-agent={{ redirectionio_agent_version }}"
    state: present
