---

- name: Add rpm repository key
  rpm_key:
    state: present
    key: http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x24765BBD8E16EB44

- name: Install redirection.io repository
  yum_repository:
    name: redirectionio
    description: redirection.io
    baseurl: "https://packages.redirection.io/rpm"
    enabled: yes
    gpgcheck: yes
    state: present

- name: Update yum cache
  yum:
    update_cache: true

- name: Install redirectionio-agent
  yum:
    name: redirectionio-agent
    state: latest
